package com.xbjornsen.emftracker.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.xbjornsen.emftracker.data.models.AlertLevel
import com.xbjornsen.emftracker.ui.theme.color

private data class InfoSection(val title: String, val body: String, val accent: Color = Color.Unspecified)

@Composable
fun AboutScreen() {
    val bodyColor = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.75f)
    val sections = listOf(
        InfoSection(
            "What is being measured?",
            "The phone's magnetometer measures the total magnetic flux density (in microteslas, µT) along three axes. " +
            "This includes Earth's static geomagnetic field (~25–65 µT depending on location), fields from nearby magnets, " +
            "and oscillating fields from AC electrical sources. Enable Baseline Subtraction to zero out the static background and isolate only what has changed."
        ),
        InfoSection(
            "Static field vs. EMF radiation",
            "A permanent magnet produces a constant (DC) field — it doesn't oscillate and is not considered EMF radiation. " +
            "AC power sources (cables, transformers, motors) produce a changing (AC) field that oscillates at 50 or 60 Hz. " +
            "Only the AC component is what EMF health research refers to.\n\n" +
            "Use the AC Variation indicator on the Live screen: if it stays near zero despite a high total reading, you are measuring a static magnet (speaker, phone case, fridge door), not radiation."
        ),
        InfoSection(
            "Why do readings change with phone orientation?",
            "Earth's magnetic field has a downward dip angle of 60–70° in mid-latitudes (northern hemisphere). " +
            "Pointing the phone up aligns the sensor's Z-axis with this dip, maximising the reading. " +
            "Pointing down reverses Z, reducing it. Total magnitude should be roughly constant with a perfectly calibrated sensor, " +
            "but phone hardware (camera OIS magnets, speakers, wireless charging coils) creates orientation-dependent offsets.\n\n" +
            "Fix: wave the phone in a figure-8 pattern several times to trigger the OS magnetometer calibration routine."
        ),
        InfoSection(
            "What does the FFT show?",
            "The Fast Fourier Transform decomposes the raw signal into its frequency components. " +
            "Each bar represents how much energy is at that frequency.\n\n" +
            "• 50 Hz / 60 Hz peaks: power-frequency mains radiation from AC wiring and appliances. This is what EMF research focuses on.\n" +
            "• Harmonics (100, 150, 200 Hz): generated by motors, dimmers, and switching power supplies — often alongside the fundamental.\n" +
            "• Low-frequency peaks (1–5 Hz): typically hand tremor or slow movement near a static magnet — not mains radiation.\n" +
            "• No peaks / flat spectrum: either no AC source nearby, or the phone is moving (motion suppresses the FFT buffer).\n\n" +
            "Tip: hold the phone very still near a phone charger or laptop power supply to see clean 50/60 Hz peaks."
        ),
        InfoSection(
            "Safe exposure limits",
            "• ICNIRP 2010 general public reference level: 200 µT at 50 Hz (continuous worst-case).\n" +
            "• WHO precautionary guideline (residential long-term average): 0.3–0.4 µT AC at power frequency.\n" +
            "• IARC classification: ELF magnetic fields are Group 2B — 'possibly carcinogenic' — based on limited epidemiological evidence in children near high-voltage power lines. This is the same category as coffee and pickled vegetables.\n\n" +
            "Context: standing 30 cm from a running microwave emits ~5–20 µT. A typical home averages 0.05–0.2 µT. The AC Variation reading (blue bar) is the number to watch — the total magnitude includes harmless static fields."
        ),
        InfoSection(
            "Pole Detection",
            "When Baseline Subtraction is active and you bring a magnet close, the app identifies north or south pole from the sign of the dominant axis of the delta vector.\n\n" +
            "North pole: field lines diverge outward — they push toward the sensor, creating a positive field component in the direction of approach.\n" +
            "South pole: field lines converge inward — they pull away from the sensor, creating a negative component.\n\n" +
            "Accuracy depends on keeping the phone still during baseline capture and approaching the magnet along a single clear axis."
        ),
        InfoSection(
            "Calibration & Limitations",
            "Consumer magnetometers are designed for compass heading, not precision EMF measurement. Typical accuracy: ±1–3 µT. " +
            "Readings are indicative and should not replace calibrated instruments for safety-critical decisions.\n\n" +
            "For best results:\n" +
            "• Do the figure-8 calibration whenever readings seem unstable.\n" +
            "• Keep the phone away from metal surfaces while measuring.\n" +
            "• Enable Motion Detection — unstable readings are suppressed automatically when the device moves.\n" +
            "• Use Baseline Subtraction in any fixed location to remove the constant Earth field and phone hardware offsets."
        )
    )

    LazyColumn(
        modifier = Modifier.fillMaxSize().padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(20.dp)
    ) {
        item {
            Text("EMF Tracker", style = MaterialTheme.typography.headlineMedium)
            Spacer(Modifier.height(4.dp))
            Text(
                "A scientific tool for measuring and analysing magnetic fields using your device's built-in magnetometer.",
                style = MaterialTheme.typography.bodyMedium, color = bodyColor
            )
        }

        item {
            Text("Alert Levels", style = MaterialTheme.typography.titleMedium)
            Spacer(Modifier.height(8.dp))
        }

        items(AlertLevel.entries) { level ->
            Row(
                verticalAlignment = Alignment.Top,
                horizontalArrangement = Arrangement.spacedBy(12.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Box(modifier = Modifier.padding(top = 4.dp).size(12.dp).background(level.color(), CircleShape))
                Column {
                    Text(level.label, style = MaterialTheme.typography.labelLarge,
                        color = level.color(), fontWeight = FontWeight.SemiBold)
                    Spacer(Modifier.height(2.dp))
                    Text(level.description, style = MaterialTheme.typography.bodySmall, color = bodyColor)
                }
            }
        }

        items(sections) { section ->
            Column {
                HorizontalDivider(modifier = Modifier.padding(bottom = 12.dp))
                Text(section.title, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)
                Spacer(Modifier.height(6.dp))
                Text(section.body, style = MaterialTheme.typography.bodySmall, color = bodyColor, lineHeight = MaterialTheme.typography.bodySmall.lineHeight)
            }
        }

        item { Spacer(Modifier.height(8.dp)) }
    }
}
